services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env
    networks:
      - rec-sys
  
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/my_cert.crt:/etc/ssl/certs/my_cert.crt
      - /etc/ssl/private/my_private.key:/etc/ssl/private/my_private.key
    depends_on:
      - app
    networks:
      - rec-sys

networks:
  rec-sys: